export interface TriviaQuestion {
  id: number;
  question: string;
  options: [string, string, string, string];
  correctIndex: number; // 0-3
  category: "lore" | "mechanics" | "tournament" | "cards" | "history";
}

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  // ============================================================
  // LORE (~40 questions) - IDs 1-40
  // ============================================================
  {
    id: 1,
    question: "What is the name of the world in which Flesh and Blood takes place?",
    options: ["Eldraine", "Dominaria", "Rathe", "Tarkir"],
    correctIndex: 2,
    category: "lore",
  },
  {
    id: 2,
    question: "Which hero is known as the 'Star of the Show' and performs in the Everfest Carnival?",
    options: ["Dorinthea", "Prism", "Kassai", "Bravo"],
    correctIndex: 3,
    category: "lore",
  },
  {
    id: 3,
    question: "What faction does Chane belong to in the lore of Rathe?",
    options: ["The Demonastery", "The Shadow Briar", "The Shadow of Embra", "The Hand of Sol"],
    correctIndex: 0,
    category: "lore",
  },
  {
    id: 4,
    question: "Dorinthea Ironsong is a knight serving which order or cause?",
    options: ["The Hand of Sol", "The Pits of the Savage Lands", "The Demonastery", "The Rosetta Guild"],
    correctIndex: 0,
    category: "lore",
  },
  {
    id: 5,
    question: "What region of Rathe is known for its dense, mystical forests and elemental magic?",
    options: ["Metrix", "Solana", "Aria", "Volcor"],
    correctIndex: 2,
    category: "lore",
  },
  {
    id: 6,
    question: "Rhinar is a brute from which savage region of Rathe?",
    options: ["The Savage Lands", "Aria", "Metrix", "Volcor"],
    correctIndex: 0,
    category: "lore",
  },
  {
    id: 7,
    question: "Which city in Rathe is known as a hub of technology and innovation?",
    options: ["Solana", "Metrix", "Volcor", "Aria"],
    correctIndex: 1,
    category: "lore",
  },
  {
    id: 8,
    question: "Dash is an inventor and mechanologist from which region?",
    options: ["Solana", "The Savage Lands", "Metrix", "The Pits"],
    correctIndex: 2,
    category: "lore",
  },
  {
    id: 9,
    question: "Prism is an Illusionist who channels the power of which source?",
    options: ["Shadow", "Ice", "Lightning", "Sol (Light)"],
    correctIndex: 3,
    category: "lore",
  },
  {
    id: 10,
    question: "Which hero wields the power of Shadow and has connections to the Demonastery?",
    options: ["Viserai", "Boltyn", "Prism", "Oldhim"],
    correctIndex: 0,
    category: "lore",
  },
  {
    id: 11,
    question: "Levia is a brute who has made a pact with which dark entity?",
    options: ["Sol", "Blasmophet", "Embra", "The Shadows of the Demonastery"],
    correctIndex: 1,
    category: "lore",
  },
  {
    id: 12,
    question: "Solana is primarily known as a city devoted to what?",
    options: ["Technology and steam power", "Shadow magic and necromancy", "Elemental ice magic", "Light, order, and the worship of Sol"],
    correctIndex: 3,
    category: "lore",
  },
  {
    id: 13,
    question: "Which ninja hero hails from the mystical land of Misteria?",
    options: ["Katsu", "Riptide", "Fai", "Benji"],
    correctIndex: 0,
    category: "lore",
  },
  {
    id: 14,
    question: "Boltyn is a warrior who fights for which cause in the lore?",
    options: ["The Demonastery", "The Everfest Carnival", "The Light of Sol", "The Savage Lands"],
    correctIndex: 2,
    category: "lore",
  },
  {
    id: 15,
    question: "Oldhim is an ancient Guardian associated with which element?",
    options: ["Ice and Earth", "Fire", "Lightning", "Shadow"],
    correctIndex: 0,
    category: "lore",
  },
  {
    id: 16,
    question: "What type of creature is Kano in the lore of Rathe?",
    options: ["A brute warlord", "A forest elemental", "A ninja assassin", "A royal wizard (Dracai)"],
    correctIndex: 3,
    category: "lore",
  },
  {
    id: 17,
    question: "Volcor is a region associated with which element and faction?",
    options: ["Ice and the Ollin", "Fire and the Royal Court / Dracai", "Earth and the Rosetta", "Lightning and the Storm"],
    correctIndex: 1,
    category: "lore",
  },
  {
    id: 18,
    question: "Dromai is a hero who summons which type of creatures in battle?",
    options: ["Spectral Shields", "Ash-born Dragons", "Mechanized Constructs", "Shadow Wraiths"],
    correctIndex: 1,
    category: "lore",
  },
  {
    id: 19,
    question: "Fai is a Ninja from which region of Rathe?",
    options: ["Volcor", "Misteria", "Metrix", "Solana"],
    correctIndex: 0,
    category: "lore",
  },
  {
    id: 20,
    question: "Briar is an Elemental Runeblade associated with which region?",
    options: ["Solana", "Metrix", "Aria (the Rosetta)", "Volcor"],
    correctIndex: 2,
    category: "lore",
  },
  {
    id: 21,
    question: "Azalea is a Ranger who operates in which environment?",
    options: [
      "The deserts of Volcor",
      "The Pits beneath the Savage Lands",
      "The streets of Metrix",
      "The jungles and wilderness near the Savage Lands",
    ],
    correctIndex: 3,
    category: "lore",
  },
  {
    id: 22,
    question: "Which hero is described as the 'Heir to Embra' in the lore?",
    options: ["Levia", "Chane", "Vynnset", "Viserai"],
    correctIndex: 2,
    category: "lore",
  },
  {
    id: 23,
    question: "What is the Everfest in the world of Rathe?",
    options: ["A traveling carnival and festival", "A military academy", "A sacred temple of Sol", "An underground fighting arena"],
    correctIndex: 0,
    category: "lore",
  },
  {
    id: 24,
    question: "Iyslander is a Wizard associated with which element?",
    options: ["Fire", "Lightning", "Earth", "Ice"],
    correctIndex: 3,
    category: "lore",
  },
  {
    id: 25,
    question: "Which hero is a Pirate-themed Ranger introduced in the Outsiders set?",
    options: ["Azalea", "Uzuri", "Riptide", "Arakni"],
    correctIndex: 2,
    category: "lore",
  },
  {
    id: 26,
    question: "Uzuri is an Assassin from which shadowy organization?",
    options: ["The Hand of Sol", "The Demonastery", "The Spider's Web (Contract network)", "The Everfest Troupe"],
    correctIndex: 2,
    category: "lore",
  },
  {
    id: 27,
    question: "Lexi is a Ranger associated with which elemental talents?",
    options: ["Ice and Lightning", "Fire and Shadow", "Earth and Water", "Light and Shadow"],
    correctIndex: 0,
    category: "lore",
  },
  {
    id: 28,
    question: "In the lore, what is the Demonastery?",
    options: [
      "A technological research facility in Metrix",
      "A dark institution where Shadow arts are practiced",
      "The ruling council of Solana",
      "A gladiatorial arena in the Savage Lands",
    ],
    correctIndex: 1,
    category: "lore",
  },
  {
    id: 29,
    question: "Which hero is an ancient Guardian who has protected Aria for centuries?",
    options: ["Bravo", "Terra", "Oldhim", "Rhinar"],
    correctIndex: 2,
    category: "lore",
  },
  {
    id: 30,
    question: "Enigma is a hero associated with which class?",
    options: ["Warrior", "Wizard", "Mechanologist", "Illusionist"],
    correctIndex: 3,
    category: "lore",
  },
  {
    id: 31,
    question: "Aurora is a hero from which class in Flesh and Blood?",
    options: ["Runeblade", "Warrior", "Guardian", "Ranger"],
    correctIndex: 0,
    category: "lore",
  },
  {
    id: 32,
    question: "What is the primary conflict in the Monarch storyline?",
    options: [
      "A war between Metrix and Volcor",
      "The destruction of the Everfest Carnival",
      "A ninja clan civil war in Misteria",
      "The struggle between Light and Shadow in Solana",
    ],
    correctIndex: 3,
    category: "lore",
  },
  {
    id: 33,
    question: "Kassai is a Warrior from which region of Rathe?",
    options: ["Volcor", "Solana", "The Savage Lands", "Aria"],
    correctIndex: 0,
    category: "lore",
  },
  {
    id: 34,
    question: "Verdance is a hero associated with which element?",
    options: ["Earth", "Ice", "Fire", "Lightning"],
    correctIndex: 0,
    category: "lore",
  },
  {
    id: 35,
    question: "Terra is a hero of which class?",
    options: ["Guardian", "Assassin", "Ninja", "Wizard"],
    correctIndex: 0,
    category: "lore",
  },
  {
    id: 36,
    question: "Nuu is an Assassin hero introduced in which set's storyline?",
    options: ["Part the Mistveil", "Monarch", "Outsiders", "Uprising"],
    correctIndex: 0,
    category: "lore",
  },
  {
    id: 37,
    question: "Zen is a Ninja hero associated with which themed region?",
    options: ["Volcor", "Metrix", "Misteria", "The Savage Lands"],
    correctIndex: 2,
    category: "lore",
  },
  {
    id: 38,
    question: "What is Viserai's primary motivation in the lore?",
    options: [
      "To protect Solana at all costs",
      "To free himself from the Arknight curse",
      "To conquer Metrix with technology",
      "To win the Everfest tournament",
    ],
    correctIndex: 1,
    category: "lore",
  },
  {
    id: 39,
    question: "Florian is a hero connected to which thematic element?",
    options: ["Shadow and death", "Fire and destruction", "Earth and nature", "Ice and preservation"],
    correctIndex: 2,
    category: "lore",
  },
  {
    id: 40,
    question: "Which region of Rathe is described as a harsh volcanic landscape ruled by the Dracai?",
    options: ["Aria", "Volcor", "Solana", "Metrix"],
    correctIndex: 1,
    category: "lore",
  },

  // ============================================================
  // MECHANICS (~40 questions) - IDs 41-80
  // ============================================================
  {
    id: 41,
    question: "How many cards does a player typically start with in their hand at the beginning of each turn in Classic Constructed?",
    options: ["5", "4", "7", "6"],
    correctIndex: 1,
    category: "mechanics",
  },
  {
    id: 42,
    question: "What resource do players use to pay for cards in Flesh and Blood?",
    options: ["Mana", "Pitch (resource points)", "Energy", "Gold"],
    correctIndex: 1,
    category: "mechanics",
  },
  {
    id: 43,
    question: "Cards with a yellow strip pitch for how many resource points?",
    options: ["1", "3", "2", "0"],
    correctIndex: 2,
    category: "mechanics",
  },
  {
    id: 44,
    question: "Cards with a blue strip pitch for how many resource points?",
    options: ["3", "2", "1", "4"],
    correctIndex: 0,
    category: "mechanics",
  },
  {
    id: 45,
    question: "Cards with a red strip pitch for how many resource points?",
    options: ["3", "2", "0", "1"],
    correctIndex: 3,
    category: "mechanics",
  },
  {
    id: 46,
    question: "What is the 'combat chain' in Flesh and Blood?",
    options: [
      "A chain of equipment cards",
      "A sequence of attack and defense steps during combat",
      "A series of instant spells",
      "The order in which heroes take turns",
    ],
    correctIndex: 1,
    category: "mechanics",
  },
  {
    id: 47,
    question: "What keyword means the defending hero can only defend with one card from hand?",
    options: ["Piercing", "Dominate", "Overpower", "Intimidate"],
    correctIndex: 1,
    category: "mechanics",
  },
  {
    id: 48,
    question: "What does the keyword 'Go Again' do?",
    options: [
      "Allows an attack to hit twice",
      "Returns the card to your hand",
      "Grants an additional action point after the action resolves",
      "Lets you draw an extra card",
    ],
    correctIndex: 2,
    category: "mechanics",
  },
  {
    id: 49,
    question: "What does the keyword 'Dominate' do on an attack?",
    options: [
      "The attack deals double damage",
      "The attack cannot be defended by more than one card from hand",
      "The opponent must discard a card",
      "The attack gains +3 power",
    ],
    correctIndex: 1,
    category: "mechanics",
  },
  {
    id: 50,
    question: "How many action points does a player typically start with on their turn?",
    options: ["1", "0", "2", "3"],
    correctIndex: 0,
    category: "mechanics",
  },
  {
    id: 51,
    question: "What happens to cards that are pitched during a turn?",
    options: [
      "They go to the graveyard",
      "They go to the bottom of the deck",
      "They are banished",
      "They return to the hand",
    ],
    correctIndex: 1,
    category: "mechanics",
  },
  {
    id: 52,
    question: "What is the minimum deck size in Classic Constructed (not including hero, equipment, or weapons)?",
    options: ["40 cards", "80 cards", "100 cards", "60 cards"],
    correctIndex: 3,
    category: "mechanics",
  },
  {
    id: 53,
    question: "How many copies of a card (by name) can you have in a Classic Constructed deck?",
    options: ["4", "3", "2", "No limit"],
    correctIndex: 1,
    category: "mechanics",
  },
  {
    id: 54,
    question: "What does the keyword 'Intimidate' do?",
    options: [
      "The attack deals extra arcane damage",
      "The opponent cannot use equipment to defend",
      "The attack gains Dominate",
      "The defending hero banishes a random card from hand",
    ],
    correctIndex: 3,
    category: "mechanics",
  },
  {
    id: 55,
    question: "What type of damage does a Wizard typically deal?",
    options: ["Physical damage", "Shadow damage", "Arcane damage", "Elemental damage"],
    correctIndex: 2,
    category: "mechanics",
  },
  {
    id: 56,
    question: "What is 'Arcane Barrier' used for?",
    options: [
      "Blocking physical attacks",
      "Increasing your attack power",
      "Drawing additional cards",
      "Preventing arcane damage by paying resources",
    ],
    correctIndex: 3,
    category: "mechanics",
  },
  {
    id: 57,
    question: "In Flesh and Blood, what is the role of equipment cards?",
    options: [
      "They serve only as cosmetic upgrades",
      "They provide defense, abilities, and can block damage",
      "They are only used in the sideboard",
      "They replace your hero card",
    ],
    correctIndex: 1,
    category: "mechanics",
  },
  {
    id: 58,
    question: "What happens when an equipment card blocks damage?",
    options: [
      "It returns to your hand",
      "It is banished from the game",
      "It remains in play but may lose defense counters or be destroyed",
      "It is destroyed and goes to the graveyard",
    ],
    correctIndex: 2,
    category: "mechanics",
  },
  {
    id: 59,
    question: "What is the 'Arsenal' zone in Flesh and Blood?",
    options: [
      "A zone where you store equipment",
      "A discard pile for pitched cards",
      "A special zone for instant cards only",
      "A face-down zone where you can place one card for use on a future turn",
    ],
    correctIndex: 3,
    category: "mechanics",
  },
  {
    id: 60,
    question: "What does the keyword 'Phantasm' do on an Illusionist's attack?",
    options: [
      "The attack cannot be blocked",
      "If the defending hero defends with a card of 6 or more power, the attack is destroyed",
      "The attack deals arcane damage instead of physical",
      "The attack returns to hand after combat",
    ],
    correctIndex: 1,
    category: "mechanics",
  },
  {
    id: 61,
    question: "How does the 'Reprise' keyword work?",
    options: [
      "The effect triggers if the attack is not blocked",
      "The effect triggers at the start of your turn",
      "The effect triggers when the card is pitched",
      "The effect triggers if the opponent has defended with at least one card from hand",
    ],
    correctIndex: 3,
    category: "mechanics",
  },
  {
    id: 62,
    question: "What does 'Opt' do in Flesh and Blood?",
    options: [
      "It lets you choose an opponent's card to destroy",
      "It lets you choose which zone a card goes to",
      "It lets you choose not to take damage",
      "It lets you look at the top card(s) of your deck and put them on top or bottom",
    ],
    correctIndex: 3,
    category: "mechanics",
  },
  {
    id: 63,
    question: "What does the 'Crush' keyword require to activate its effect?",
    options: [
      "The attack must deal 4 or more damage",
      "The card must be played from Arsenal",
      "The attack must be unblocked entirely",
      "The attack must deal damage (at least 1) to the opponent's hero",
    ],
    correctIndex: 0,
    category: "mechanics",
  },
  {
    id: 64,
    question: "What is a 'Token' card in Flesh and Blood?",
    options: [
      "A card that represents currency in-game",
      "A card created by an effect that exists in play (like Spectral Shield or Aura tokens)",
      "A special foil variant of a regular card",
      "A placeholder for a banned card",
    ],
    correctIndex: 1,
    category: "mechanics",
  },
  {
    id: 65,
    question: "What does the 'Blade Break' effect on an equipment card mean?",
    options: [
      "The equipment gains +1 attack",
      "The equipment can only be used once per game",
      "The equipment cannot be targeted by attacks",
      "The equipment is destroyed after it is used to defend",
    ],
    correctIndex: 3,
    category: "mechanics",
  },
  {
    id: 66,
    question: "What is the starting life total for a hero in Classic Constructed?",
    options: ["20", "It varies by hero", "30", "40"],
    correctIndex: 1,
    category: "mechanics",
  },
  {
    id: 67,
    question: "What does the term 'on-hit effect' mean in Flesh and Blood?",
    options: [
      "An effect that triggers when an attack deals damage to the opposing hero",
      "An effect that triggers when you block",
      "An effect that triggers when a card is played",
      "An effect that triggers when a card is pitched",
    ],
    correctIndex: 0,
    category: "mechanics",
  },
  {
    id: 68,
    question: "What is the 'Banished' zone?",
    options: [
      "Another name for the graveyard",
      "The zone where pitched cards go",
      "A zone only used in Blitz format",
      "A zone for cards removed from the game that can sometimes still be interacted with",
    ],
    correctIndex: 3,
    category: "mechanics",
  },
  {
    id: 69,
    question: "In Blitz format, what is the typical starting hand size?",
    options: ["4", "3", "5", "6"],
    correctIndex: 0,
    category: "mechanics",
  },
  {
    id: 70,
    question: "What is the minimum deck size in Blitz format?",
    options: ["30 cards", "40 cards", "50 cards", "60 cards"],
    correctIndex: 1,
    category: "mechanics",
  },
  {
    id: 71,
    question: "What does 'Heave' allow a Guardian hero to do?",
    options: [
      "Attack with double power",
      "Pay extra resources to play an attack from the bottom of the deck",
      "If the card is in hand at end of turn, you may pay its cost to activate an effect",
      "Draw cards equal to the card's defense value",
    ],
    correctIndex: 2,
    category: "mechanics",
  },
  {
    id: 72,
    question: "What does the 'Combo' keyword do on Ninja attack actions?",
    options: [
      "Allows the card to be played without paying its cost",
      "Lets you play two attacks simultaneously",
      "Makes the attack unblockable",
      "Grants a bonus if the previous attack in the combat chain was a specific card",
    ],
    correctIndex: 3,
    category: "mechanics",
  },
  {
    id: 73,
    question: "How does 'Blood Debt' work for Levia?",
    options: [
      "You gain life equal to damage dealt",
      "At end of turn, if you have cards with Blood Debt in the banished zone, you lose life if you haven't banished enough cards",
      "You pay life to increase your attack power",
      "Your opponent loses life whenever you pitch a card",
    ],
    correctIndex: 1,
    category: "mechanics",
  },
  {
    id: 74,
    question: "What does the 'Spectra' keyword relate to?",
    options: [
      "Cards that can only be played during the opponent's turn",
      "Equipment that provides Arcane Barrier",
      "Illusionist cards and aura/spectral token effects",
      "Cards that deal both arcane and physical damage",
    ],
    correctIndex: 2,
    category: "mechanics",
  },
  {
    id: 75,
    question: "What is a 'Defense Reaction' card?",
    options: [
      "A card played during your turn to boost defense",
      "A card that automatically blocks all damage",
      "A card that can only be placed in the Arsenal",
      "A card that can be played from hand during the opponent's turn to defend",
    ],
    correctIndex: 3,
    category: "mechanics",
  },
  {
    id: 76,
    question: "What does 'Spellvoid' do on an equipment card?",
    options: [
      "Provides Arcane Barrier that destroys the equipment after use",
      "Prevents physical damage",
      "Makes the equipment immune to destruction",
      "Allows the equipment to block attacks twice",
    ],
    correctIndex: 0,
    category: "mechanics",
  },
  {
    id: 77,
    question: "What are 'Instant' cards in Flesh and Blood?",
    options: [
      "Cards that can only be played on your turn",
      "Cards that cost 0 resources",
      "Cards that can be played at almost any time, including the opponent's turn",
      "Cards that immediately win the game",
    ],
    correctIndex: 2,
    category: "mechanics",
  },
  {
    id: 78,
    question: "What does 'Temper' do on an equipment card?",
    options: [
      "It gains an ability until end of turn",
      "The equipment provides +1 to all attacks",
      "When it defends, it gets a -1 defense counter; destroyed at 0 defense",
      "When the equipment would be destroyed, instead put a -1 counter on it",
    ],
    correctIndex: 2,
    category: "mechanics",
  },
  {
    id: 79,
    question: "What does the keyword 'Battleworn' do on equipment?",
    options: [
      "The equipment cannot block",
      "The equipment is destroyed at end of turn",
      "When the equipment defends, put a -1 defense counter on it",
      "The equipment costs 1 more to use each turn",
    ],
    correctIndex: 2,
    category: "mechanics",
  },
  {
    id: 80,
    question: "What does the term 'pitch stack' refer to in Flesh and Blood strategy?",
    options: [
      "The stack of cards in the Arsenal",
      "A stack of resource tokens",
      "The pile of destroyed equipment",
      "The ordered pile of pitched cards that will become your future deck draws",
    ],
    correctIndex: 3,
    category: "mechanics",
  },

  // ============================================================
  // TOURNAMENT (~40 questions) - IDs 81-120
  // ============================================================
  {
    id: 81,
    question: "What is the highest level of competitive Flesh and Blood tournament called?",
    options: ["Pro Tour", "Grand Prix", "Calling", "World Championship"],
    correctIndex: 3,
    category: "tournament",
  },
  {
    id: 82,
    question: "What is a 'Calling' event in Flesh and Blood organized play?",
    options: [
      "A local game store tournament",
      "A premier-level competitive event held in major cities worldwide",
      "An online-only tournament format",
      "A casual league event",
    ],
    correctIndex: 1,
    category: "tournament",
  },
  {
    id: 83,
    question: "What happens to a hero that reaches 'Living Legend' status?",
    options: [
      "The hero gets a special foil reprint",
      "The hero is banned from competitive Constructed formats",
      "The hero gains extra life in tournaments",
      "The hero can only be used in Blitz",
    ],
    correctIndex: 1,
    category: "tournament",
  },
  {
    id: 84,
    question: "Which format uses a 60-card minimum deck with adult heroes?",
    options: ["Classic Constructed", "Blitz", "Draft", "Sealed"],
    correctIndex: 0,
    category: "tournament",
  },
  {
    id: 85,
    question: "Which format uses a 40-card minimum deck with young heroes?",
    options: ["Classic Constructed", "Draft", "Living Legend", "Blitz"],
    correctIndex: 3,
    category: "tournament",
  },
  {
    id: 86,
    question: "What is 'Booster Draft' in Flesh and Blood?",
    options: [
      "A format where players buy random boosters and build decks from them independently",
      "A format where only the rarest cards can be used",
      "A format where players open packs and pass cards to draft their deck",
      "A format limited to two players",
    ],
    correctIndex: 2,
    category: "tournament",
  },
  {
    id: 87,
    question: "In a Sealed Deck tournament, how many booster packs does each player typically open?",
    options: ["6", "4", "8", "3"],
    correctIndex: 0,
    category: "tournament",
  },
  {
    id: 88,
    question: "What is a 'Pro Tour' event in Flesh and Blood?",
    options: [
      "A local qualifier event",
      "An invitation-only premier competitive event",
      "A casual fun event at conventions",
      "An online streaming event",
    ],
    correctIndex: 1,
    category: "tournament",
  },
  {
    id: 89,
    question: "What is the 'Road to Nationals' program?",
    options: [
      "A fitness program for FaB players",
      "A deck-building tutorial series",
      "A series of qualifier events leading to National Championship tournaments",
      "A lore-based storyline campaign",
    ],
    correctIndex: 2,
    category: "tournament",
  },
  {
    id: 90,
    question: "Which hero was the first to achieve Living Legend status?",
    options: ["Bravo, Star of the Show", "Prism", "Chane", "Katsu"],
    correctIndex: 0,
    category: "tournament",
  },
  {
    id: 91,
    question: "What organization runs the official Flesh and Blood organized play?",
    options: ["Legend Story Studios", "Wizards of the Coast", "Bushiroad", "Konami"],
    correctIndex: 0,
    category: "tournament",
  },
  {
    id: 92,
    question: "The 'GEM' system in Flesh and Blood stands for what?",
    options: [
      "Gathering of Elite Masters",
      "Global Event Management",
      "Game Enhancement Module",
      "Game Event Manager",
    ],
    correctIndex: 3,
    category: "tournament",
  },
  {
    id: 93,
    question: "What is the typical time limit for a round in a Flesh and Blood tournament?",
    options: ["30 minutes", "50 minutes", "40 minutes", "60 minutes"],
    correctIndex: 1,
    category: "tournament",
  },
  {
    id: 94,
    question: "What format is typically used in the draft portion of a Pro Tour?",
    options: ["Classic Constructed", "Sealed Deck", "Blitz", "Booster Draft"],
    correctIndex: 3,
    category: "tournament",
  },
  {
    id: 95,
    question: "In competitive play, what is a 'sideboard' used for in Flesh and Blood?",
    options: [
      "A 15-card sideboard like Magic: The Gathering",
      "FaB doesn't use a traditional sideboard; the full inventory is your deck and equipment",
      "A 10-card sideboard swapped between games",
      "An extra set of hero cards",
    ],
    correctIndex: 1,
    category: "tournament",
  },
  {
    id: 96,
    question: "What was the format of the first Flesh and Blood World Championship?",
    options: ["Blitz only", "Classic Constructed only", "Sealed only", "Classic Constructed and Booster Draft"],
    correctIndex: 3,
    category: "tournament",
  },
  {
    id: 97,
    question: "What is a 'Skirmish' event in Flesh and Blood?",
    options: [
      "A seasonal competitive event at local game stores with promo prizes",
      "A team-based tournament format",
      "A 1v1 casual game",
      "A quick-play version of Blitz",
    ],
    correctIndex: 0,
    category: "tournament",
  },
  {
    id: 98,
    question: "What is the 'Banned and Restricted' list in Flesh and Blood?",
    options: [
      "A list of players who are banned from events",
      "A list of stores that cannot host events",
      "A list of retired heroes only",
      "A list of cards that cannot be used or are limited in competitive formats",
    ],
    correctIndex: 3,
    category: "tournament",
  },
  {
    id: 99,
    question: "Which hero achieved Living Legend in Classic Constructed due to dominance in the Monarch era?",
    options: ["Chane", "Prism", "Boltyn", "Levia"],
    correctIndex: 0,
    category: "tournament",
  },
  {
    id: 100,
    question: "How many players typically participate in a Calling event at peak attendance?",
    options: ["50-100", "100-300", "2000-5000", "500-1500+"],
    correctIndex: 3,
    category: "tournament",
  },
  {
    id: 101,
    question: "Which of the following is NOT a valid competitive format in Flesh and Blood?",
    options: ["Classic Constructed", "Commander", "Blitz", "Booster Draft"],
    correctIndex: 1,
    category: "tournament",
  },
  {
    id: 102,
    question: "In tournament play, can you look at your own pitch zone (bottom of your deck)?",
    options: [
      "Yes, at any time",
      "Only during your turn",
      "Only if a card effect allows it",
      "No, the order of your deck is hidden information",
    ],
    correctIndex: 3,
    category: "tournament",
  },
  {
    id: 103,
    question: "What is the 'Armory' event series in FaB organized play?",
    options: [
      "A national-level tournament series",
      "Weekly/regular events at local game stores with kit prizes",
      "An online event platform",
      "A pre-release event series",
    ],
    correctIndex: 1,
    category: "tournament",
  },
  {
    id: 104,
    question: "Bravo, Star of the Show was the first hero to achieve Living Legend in which format?",
    options: ["Classic Constructed", "Draft", "Blitz", "Both simultaneously"],
    correctIndex: 0,
    category: "tournament",
  },
  {
    id: 105,
    question: "What tiebreaker is commonly used in Swiss rounds of FaB tournaments?",
    options: [
      "Coin flip",
      "Rock Paper Scissors",
      "Opponent Match Win Percentage",
      "Hero alphabetical order",
    ],
    correctIndex: 2,
    category: "tournament",
  },
  {
    id: 106,
    question: "In a best-of-one tournament match, what happens if time is called?",
    options: [
      "The game immediately ends in a draw",
      "Players complete the current turn cycle, then the player with more life wins",
      "Players play sudden death",
      "The attacking player automatically wins",
    ],
    correctIndex: 1,
    category: "tournament",
  },
  {
    id: 107,
    question: "What is the 'ProQuest' event series?",
    options: [
      "A qualifier event series for Pro Tour invitations",
      "A beginner tutorial event",
      "A team-based event format",
      "A limited format event",
    ],
    correctIndex: 0,
    category: "tournament",
  },
  {
    id: 108,
    question: "What is the penalty for drawing extra cards accidentally in a competitive FaB tournament?",
    options: [
      "Automatic game loss",
      "Disqualification",
      "No penalty",
      "Warning for the first offense, with the drawn card revealed and put back",
    ],
    correctIndex: 3,
    category: "tournament",
  },
  {
    id: 109,
    question: "How are pairings typically determined in Swiss rounds?",
    options: [
      "Randomly each round",
      "Players with similar records are paired together",
      "Based on hero class matchups",
      "By player ranking from previous events only",
    ],
    correctIndex: 1,
    category: "tournament",
  },
  {
    id: 110,
    question: "What is the 'Battle Hardened' event series in FaB?",
    options: [
      "A casual beginner series",
      "An online-only tournament series",
      "A premier competitive event tier between Skirmish and Calling",
      "A team draft format",
    ],
    correctIndex: 2,
    category: "tournament",
  },
  {
    id: 111,
    question: "Which hero famously dominated the metagame before being banned or reaching Living Legend?",
    options: ["Briar, Warden of Thorns", "Oldhim", "Azalea", "Riptide"],
    correctIndex: 0,
    category: "tournament",
  },
  {
    id: 112,
    question: "What unique competitive feature does Flesh and Blood have that many other TCGs do not?",
    options: [
      "Best-of-five matches",
      "Team-based play only",
      "No banlist",
      "The pitch/deck cycling system creating a second cycle deck",
    ],
    correctIndex: 3,
    category: "tournament",
  },
  {
    id: 113,
    question: "What is the typical deck registration requirement at premier events?",
    options: [
      "No deck registration needed",
      "Players must submit a full decklist including hero, equipment, weapons, and all cards",
      "Only the hero must be registered",
      "Only cards over a certain rarity must be registered",
    ],
    correctIndex: 1,
    category: "tournament",
  },
  {
    id: 114,
    question: "In competitive FaB, when do players present their deck to the opponent?",
    options: [
      "Before each game for shuffling/cutting",
      "Never; self-shuffle only",
      "Only at the start of the first game",
      "Only when requested by a judge",
    ],
    correctIndex: 0,
    category: "tournament",
  },
  {
    id: 115,
    question: "What does the 'XP' system track in FaB organized play?",
    options: [
      "In-game experience for hero leveling",
      "Store loyalty rewards",
      "Card collection progress",
      "Player competitive points earned from events for qualifications and rankings",
    ],
    correctIndex: 3,
    category: "tournament",
  },
  {
    id: 116,
    question: "What is a 'Pre-Release' event in Flesh and Blood?",
    options: [
      "An event where players can play with a new set before its official release date",
      "A tournament held after a set rotates out",
      "A special format using only old sets",
      "An online preview stream",
    ],
    correctIndex: 0,
    category: "tournament",
  },
  {
    id: 117,
    question: "Starvo (Bravo, Star of the Show) reached Living Legend primarily due to dominance with which strategy?",
    options: [
      "Aggressive combo attacks",
      "Arcane damage wizardry",
      "Ninja combo chains",
      "Defensive Guardian gameplay with powerful equipment and Phantasm poppers",
    ],
    correctIndex: 3,
    category: "tournament",
  },
  {
    id: 118,
    question: "In Flesh and Blood tournaments, what is the 'inventory' concept?",
    options: [
      "A list of all cards a player owns",
      "The pool of cards you registered including your deck and all possible equipment/weapon swaps",
      "A shop where players buy cards between rounds",
      "The judge's list of available penalty cards",
    ],
    correctIndex: 1,
    category: "tournament",
  },
  {
    id: 119,
    question: "What country hosted the first Flesh and Blood World Championship?",
    options: ["United States", "New Zealand", "Japan", "Australia"],
    correctIndex: 0,
    category: "tournament",
  },
  {
    id: 120,
    question: "In competitive play, what is the purpose of the 'start of game procedure'?",
    options: [
      "To determine prize support",
      "To register your decklist",
      "To establish the best-of-three match format",
      "Players reveal heroes, choose equipment/weapons, and determine who goes first",
    ],
    correctIndex: 3,
    category: "tournament",
  },

  // ============================================================
  // CARDS (~40 questions) - IDs 121-160
  // ============================================================
  {
    id: 121,
    question: "Which iconic Warrior weapon is Dorinthea's signature sword?",
    options: ["Dawnblade", "Hatchet of Body", "Cintari Saber", "Nebula Blade"],
    correctIndex: 0,
    category: "cards",
  },
  {
    id: 122,
    question: "What is the name of Rhinar's signature weapon?",
    options: ["Mandible Claw", "Romping Club", "Scabskin Leathers", "Ravenous Meataxe"],
    correctIndex: 1,
    category: "cards",
  },
  {
    id: 123,
    question: "Which card is an iconic Majestic equipment from the Ninja class known for rewarding on-hit attacks?",
    options: ["Enlightened Strike", "Kodachi", "Lord of Wind", "Mask of Momentum"],
    correctIndex: 3,
    category: "cards",
  },
  {
    id: 124,
    question: "What is the name of Bravo's signature weapon?",
    options: ["Anothos", "Sledge of Anvilheim", "Titan's Fist", "Winter's Wail"],
    correctIndex: 0,
    category: "cards",
  },
  {
    id: 125,
    question: "Which Legendary equipment is famous for being one of the most expensive cards in FaB?",
    options: ["Arcanite Skullcap", "Crown of Seeds", "Fyendal's Spring Tunic", "Nullrune Hood"],
    correctIndex: 2,
    category: "cards",
  },
  {
    id: 126,
    question: "What does the card 'Enlightened Strike' do?",
    options: [
      "It's a powerful Generic attack that lets you choose: draw a card, gain power, or gain go again",
      "It's an Instant that prevents all damage",
      "It's a 0-cost attack with Go Again",
      "It's a Defense Reaction that gains you life",
    ],
    correctIndex: 0,
    category: "cards",
  },
  {
    id: 127,
    question: "The card 'Art of War' is known for being what rarity?",
    options: ["Rare", "Fabled", "Super Rare", "Majestic"],
    correctIndex: 1,
    category: "cards",
  },
  {
    id: 128,
    question: "Which card is Viserai's signature weapon?",
    options: ["Nebula Blade", "Rosetta Thorn", "Reaping Blade", "Shadow of Embra"],
    correctIndex: 0,
    category: "cards",
  },
  {
    id: 129,
    question: "'Command and Conquer' is an iconic card of which type?",
    options: ["Defense Reaction", "Attack Action", "Instant", "Attack Reaction"],
    correctIndex: 1,
    category: "cards",
  },
  {
    id: 130,
    question: "What is the Fabled rarity card from Welcome to Rathe?",
    options: ["Arknight Ascendancy", "Eye of Ophidia", "Galaxxi Black", "Heart of Fyendal"],
    correctIndex: 3,
    category: "cards",
  },
  {
    id: 131,
    question: "Which card is a well-known Generic equipment piece that provides resource generation?",
    options: ["Nullrune Hood", "Snapdragon Scalers", "Fyendal's Spring Tunic", "Arcanite Skullcap"],
    correctIndex: 2,
    category: "cards",
  },
  {
    id: 132,
    question: "Katsu's hero ability involves which mechanic?",
    options: [
      "Gaining action points",
      "Dealing arcane damage",
      "Creating Spectral Shield tokens",
      "Searching for combo pieces when a Combo card hits",
    ],
    correctIndex: 3,
    category: "cards",
  },
  {
    id: 133,
    question: "What is the Fabled rarity card from Arcane Rising?",
    options: ["Heart of Fyendal", "Eye of Ophidia", "Arknight Ascendancy", "Command and Conquer"],
    correctIndex: 2,
    category: "cards",
  },
  {
    id: 134,
    question: "'Sink Below' is a well-known card of which type?",
    options: ["Attack Action", "Instant", "Defense Reaction", "Attack Reaction"],
    correctIndex: 2,
    category: "cards",
  },
  {
    id: 135,
    question: "The card 'Pummel' is primarily used as what type of card?",
    options: ["Defense Reaction", "Attack Reaction that gives +4 power", "Instant", "Non-attack Action"],
    correctIndex: 1,
    category: "cards",
  },
  {
    id: 136,
    question: "Which Ninja weapon allows multiple attacks per turn due to being a one-handed weapon?",
    options: ["Zephyr Needle", "Harmonized Kodachi", "Dawnblade", "Tiger Stripe Shuko"],
    correctIndex: 1,
    category: "cards",
  },
  {
    id: 137,
    question: "What does the card 'Tome of Fyendal' do?",
    options: [
      "Deal 10 arcane damage",
      "Draw 2 cards; if played from arsenal, gain life equal to cards in hand",
      "Search your deck for any card",
      "Destroy an equipment",
    ],
    correctIndex: 1,
    category: "cards",
  },
  {
    id: 138,
    question: "'Snapdragon Scalers' is a Generic equipment piece that provides what?",
    options: [
      "Arcane Barrier 1",
      "+1 defense",
      "Card draw",
      "Go Again to the next attack you play",
    ],
    correctIndex: 3,
    category: "cards",
  },
  {
    id: 139,
    question: "Dash's hero ability relates to which mechanic?",
    options: [
      "Dealing arcane damage from hand",
      "Banishing the top card of your deck to use Boost",
      "Creating Spectral Shield tokens",
      "Searching for combo attacks",
    ],
    correctIndex: 1,
    category: "cards",
  },
  {
    id: 140,
    question: "Which card is the Fabled from Crucible of War?",
    options: ["Heart of Fyendal", "Great Library of Solana", "Eye of Ophidia", "Arknight Ascendancy"],
    correctIndex: 2,
    category: "cards",
  },
  {
    id: 141,
    question: "What is Prism's primary token type that she creates?",
    options: ["Spectral Shield tokens", "Quicken tokens", "Ash tokens", "Runechant tokens"],
    correctIndex: 0,
    category: "cards",
  },
  {
    id: 142,
    question: "'Runechant' tokens are primarily associated with which class?",
    options: ["Illusionist", "Wizard", "Runeblade", "Guardian"],
    correctIndex: 2,
    category: "cards",
  },
  {
    id: 143,
    question: "What type of token does Dromai create?",
    options: ["Spectral Shield tokens", "Ash (Dragon) tokens", "Runechant tokens", "Quicken tokens"],
    correctIndex: 1,
    category: "cards",
  },
  {
    id: 144,
    question: "The card 'Sigil of Solace' is known for what effect?",
    options: [
      "Dealing 3 damage",
      "Gaining life",
      "Drawing 2 cards",
      "Destroying an aura",
    ],
    correctIndex: 1,
    category: "cards",
  },
  {
    id: 145,
    question: "Which equipment piece is known for providing both Arcane Barrier and physical defense?",
    options: ["Arcanite Skullcap", "Nullrune Gloves", "Fyendal's Spring Tunic", "Crown of Seeds"],
    correctIndex: 0,
    category: "cards",
  },
  {
    id: 146,
    question: "What is the name of Kano's signature weapon?",
    options: ["Waning Moon", "Crucible of Aetherweave", "Aether Ironweave", "Metacarpus Node"],
    correctIndex: 1,
    category: "cards",
  },
  {
    id: 147,
    question: "'Codex of Frailty' is associated with which type of card effect?",
    options: [
      "Boosting attack power",
      "Reducing the opponent's defense",
      "Gaining life points",
      "Applying a debuff (Frailty) to the opposing hero",
    ],
    correctIndex: 3,
    category: "cards",
  },
  {
    id: 148,
    question: "Which Generic attack action has become a staple in many aggressive decks due to its 'on-hit' draw effect?",
    options: ["Enlightened Strike", "Snatch", "Razor Reflex", "Sink Below"],
    correctIndex: 1,
    category: "cards",
  },
  {
    id: 149,
    question: "What type of card is 'Courage of Bladehold'?",
    options: ["Attack Action", "Defense Reaction", "Equipment", "Attack Reaction"],
    correctIndex: 2,
    category: "cards",
  },
  {
    id: 150,
    question: "The Nullrune equipment set is valued in competitive play primarily for what?",
    options: [
      "Providing Arcane Barrier to counter Wizard and Runeblade arcane damage",
      "Granting Go Again",
      "High physical defense values",
      "Boosting attack power",
    ],
    correctIndex: 0,
    category: "cards",
  },
  {
    id: 151,
    question: "Which card allows you to banish cards from your opponent's graveyard?",
    options: ["Soul Reaping", "Ghostly Visit", "Rift Bind", "Rifting"],
    correctIndex: 3,
    category: "cards",
  },
  {
    id: 152,
    question: "What is the maximum number of weapon slots a hero can typically have?",
    options: ["1", "2", "It varies by hero", "3"],
    correctIndex: 2,
    category: "cards",
  },
  {
    id: 153,
    question: "The card 'Wounded Bull' is thematically associated with which class?",
    options: ["Brute", "Warrior", "Ninja", "Guardian"],
    correctIndex: 0,
    category: "cards",
  },
  {
    id: 154,
    question: "'Mask of Momentum' is a Legendary equipment for which class?",
    options: ["Warrior", "Brute", "Ninja", "Illusionist"],
    correctIndex: 2,
    category: "cards",
  },
  {
    id: 155,
    question: "Which card is Azalea's signature weapon?",
    options: ["Voltaire", "Bull's Eye Bracers", "Remorseless", "Death Dealer"],
    correctIndex: 3,
    category: "cards",
  },
  {
    id: 156,
    question: "What does the card 'Fate Foreseen' do?",
    options: [
      "Draw 2 cards",
      "It's a Defense Reaction that defends for 4 and lets you Opt 1",
      "Deal 4 arcane damage",
      "Create 2 Spectral Shield tokens",
    ],
    correctIndex: 1,
    category: "cards",
  },
  {
    id: 157,
    question: "'Galaxxi Black' is a Legendary weapon for which hero?",
    options: ["Dash", "Viserai", "Kano", "Iyslander"],
    correctIndex: 0,
    category: "cards",
  },
  {
    id: 158,
    question: "Which equipment head piece is widely considered one of the best Generic helmets in the game?",
    options: ["Crown of Seeds", "Nullrune Hood", "Ironhide Helm", "Arcanite Skullcap"],
    correctIndex: 3,
    category: "cards",
  },
  {
    id: 159,
    question: "What type of card is 'Red in the Ledger'?",
    options: ["Generic Action", "Attack Action", "Instant", "Defense Reaction"],
    correctIndex: 1,
    category: "cards",
  },
  {
    id: 160,
    question: "The 'Tunic' in 'Fyendal's Spring Tunic' provides what ability?",
    options: [
      "Arcane Barrier 2",
      "Draw a card at the start of each turn",
      "+2 defense to all attacks",
      "Accumulates energy counters; remove 3 to gain 1 resource as an instant",
    ],
    correctIndex: 3,
    category: "cards",
  },

  // ============================================================
  // HISTORY (~45 questions) - IDs 161-205
  // ============================================================
  {
    id: 161,
    question: "In what year was Flesh and Blood's first set, Welcome to Rathe, released?",
    options: ["2019", "2018", "2020", "2017"],
    correctIndex: 0,
    category: "history",
  },
  {
    id: 162,
    question: "Which company created Flesh and Blood?",
    options: ["Wizards of the Coast", "Fantasy Flight Games", "Legend Story Studios", "Bushiroad"],
    correctIndex: 2,
    category: "history",
  },
  {
    id: 163,
    question: "In which country was Legend Story Studios founded?",
    options: ["New Zealand", "Australia", "Japan", "United States"],
    correctIndex: 0,
    category: "history",
  },
  {
    id: 164,
    question: "What was the second main set released for Flesh and Blood?",
    options: ["Arcane Rising", "Crucible of War", "Monarch", "Tales of Aria"],
    correctIndex: 0,
    category: "history",
  },
  {
    id: 165,
    question: "Which set introduced the Monarch archetype and the Light/Shadow talent?",
    options: ["Monarch", "Arcane Rising", "Tales of Aria", "Uprising"],
    correctIndex: 0,
    category: "history",
  },
  {
    id: 166,
    question: "Tales of Aria introduced which elemental talents?",
    options: [
      "Fire, Water, and Wind",
      "Ice, Earth, and Lightning",
      "Light, Shadow, and Fire",
      "Fire, Ice, and Shadow",
    ],
    correctIndex: 1,
    category: "history",
  },
  {
    id: 167,
    question: "Which set was the first 'supplementary' set (not a main booster set) for Flesh and Blood?",
    options: ["Crucible of War", "Monarch", "Everfest", "Dynasty"],
    correctIndex: 0,
    category: "history",
  },
  {
    id: 168,
    question: "The Uprising set is thematically set in which region of Rathe?",
    options: ["Aria", "Volcor", "Solana", "Metrix"],
    correctIndex: 1,
    category: "history",
  },
  {
    id: 169,
    question: "Which set introduced the Assassin class to Flesh and Blood?",
    options: ["Monarch", "Dynasty", "Uprising", "Outsiders"],
    correctIndex: 3,
    category: "history",
  },
  {
    id: 170,
    question: "Bright Lights is a set primarily focused on which region and class?",
    options: [
      "Solana and Warriors",
      "Volcor and Wizards",
      "Aria and Guardians",
      "Metrix and Mechanologists",
    ],
    correctIndex: 3,
    category: "history",
  },
  {
    id: 171,
    question: "Who is the founder and CEO of Legend Story Studios?",
    options: ["James White", "Richard Garfield", "Mark Rosewater", "Jason Chung"],
    correctIndex: 0,
    category: "history",
  },
  {
    id: 172,
    question: "What was notable about the first edition Alpha printing of Welcome to Rathe?",
    options: [
      "It was print-to-demand",
      "It was only available in New Zealand",
      "It was a digital-only release",
      "It had an extremely limited print run and cards became highly collectible",
    ],
    correctIndex: 3,
    category: "history",
  },
  {
    id: 173,
    question: "The 'Flesh and Blood' World Premiere took place in which year?",
    options: ["2018", "2020", "2021", "2019"],
    correctIndex: 3,
    category: "history",
  },
  {
    id: 174,
    question: "Which set introduced the Illusionist class?",
    options: ["Monarch", "Arcane Rising", "Tales of Aria", "Everfest"],
    correctIndex: 0,
    category: "history",
  },
  {
    id: 175,
    question: "The Dynasty set focused on heroes from which region?",
    options: ["Volcor", "Aria", "Metrix", "The Savage Lands"],
    correctIndex: 0,
    category: "history",
  },
  {
    id: 176,
    question: "Everfest was a supplementary set themed around what?",
    options: [
      "A military conflict",
      "An underwater adventure",
      "The traveling Everfest Carnival",
      "A space exploration theme",
    ],
    correctIndex: 2,
    category: "history",
  },
  {
    id: 177,
    question: "What year did Flesh and Blood hold its first official World Championship?",
    options: ["2019", "2021", "2020", "2022"],
    correctIndex: 3,
    category: "history",
  },
  {
    id: 178,
    question: "Heavy Hitters introduced heroes from which class archetype?",
    options: ["Ninja and Wizard", "Brute, Guardian, and Warrior", "Guardian and Warrior", "Assassin and Ranger"],
    correctIndex: 1,
    category: "history",
  },
  {
    id: 179,
    question: "Which set returned to the region of Aria with new Elemental heroes?",
    options: ["Everfest", "Rosetta", "Heavy Hitters", "Outsiders"],
    correctIndex: 1,
    category: "history",
  },
  {
    id: 180,
    question: "The Dusk till Dawn set focused on which thematic conflict?",
    options: [
      "Fire vs. Ice elementals",
      "Technology vs. Nature",
      "Ninjas vs. Brutes",
      "Light vs. Shadow in Solana",
    ],
    correctIndex: 3,
    category: "history",
  },
  {
    id: 181,
    question: "What significant change did Legend Story Studios announce regarding set structure in 2023?",
    options: [
      "Moving to digital-only releases",
      "Canceling all supplementary sets",
      "Releasing sets in a more thematic, regional focus with smaller, more frequent releases",
      "Switching to a collectible miniatures game",
    ],
    correctIndex: 2,
    category: "history",
  },
  {
    id: 182,
    question: "Welcome to Rathe introduced how many heroes?",
    options: ["4", "2", "6", "8"],
    correctIndex: 0,
    category: "history",
  },
  {
    id: 183,
    question: "Which four heroes were in Welcome to Rathe?",
    options: [
      "Prism, Chane, Levia, Boltyn",
      "Bravo, Dorinthea, Katsu, Rhinar",
      "Dash, Azalea, Viserai, Kano",
      "Briar, Oldhim, Lexi, Iyslander",
    ],
    correctIndex: 1,
    category: "history",
  },
  {
    id: 184,
    question: "Which four heroes were introduced in Arcane Rising?",
    options: [
      "Bravo, Dorinthea, Katsu, Rhinar",
      "Prism, Levia, Chane, Boltyn",
      "Fai, Dromai, Iyslander, Kassai",
      "Dash, Azalea, Viserai, Kano",
    ],
    correctIndex: 3,
    category: "history",
  },
  {
    id: 185,
    question: "In what year was Arcane Rising released?",
    options: ["2020", "2019", "2021", "2022"],
    correctIndex: 0,
    category: "history",
  },
  {
    id: 186,
    question: "The COVID-19 pandemic had what effect on early Flesh and Blood organized play?",
    options: [
      "No effect at all",
      "It only affected New Zealand events",
      "It caused the game to be canceled permanently",
      "It delayed organized play and caused many early events to be online or postponed",
    ],
    correctIndex: 3,
    category: "history",
  },
  {
    id: 187,
    question: "What milestone did Flesh and Blood achieve that brought mainstream attention in 2021?",
    options: [
      "First FaB video game released",
      "Alpha first edition cards selling for record prices, high-profile box breaks, and explosive growth",
      "Partnership with Nintendo",
      "A Flesh and Blood movie announcement",
    ],
    correctIndex: 1,
    category: "history",
  },
  {
    id: 188,
    question: "Which set was the first to be released in 2022?",
    options: ["Uprising", "Everfest", "Dynasty", "Outsiders"],
    correctIndex: 1,
    category: "history",
  },
  {
    id: 189,
    question: "Part the Mistveil is thematically set in which region?",
    options: ["Volcor", "Misteria", "Metrix", "Solana"],
    correctIndex: 1,
    category: "history",
  },
  {
    id: 190,
    question: "What was the first Flesh and Blood Fabled card ever printed?",
    options: ["Eye of Ophidia", "Arknight Ascendancy", "Heart of Fyendal", "Great Library of Solana"],
    correctIndex: 2,
    category: "history",
  },
  {
    id: 191,
    question: "The Hunted set introduced heroes dealing with what thematic storyline?",
    options: [
      "A hunt involving Rangers and predatory creatures",
      "A deep-sea exploration arc",
      "A tournament arc in the Everfest Carnival",
      "A time-travel storyline",
    ],
    correctIndex: 0,
    category: "history",
  },
  {
    id: 192,
    question: "Which set first introduced the Ranger class to Flesh and Blood?",
    options: ["Arcane Rising", "Crucible of War", "Welcome to Rathe", "Tales of Aria"],
    correctIndex: 0,
    category: "history",
  },
  {
    id: 193,
    question: "Monarch was released in which year?",
    options: ["2021", "2020", "2022", "2023"],
    correctIndex: 0,
    category: "history",
  },
  {
    id: 194,
    question: "What type of product was 'History Pack 1'?",
    options: [
      "A booster set with new cards",
      "A reprint set making Welcome to Rathe and Arcane Rising cards more accessible",
      "A sealed deck starter kit",
      "A lore book",
    ],
    correctIndex: 1,
    category: "history",
  },
  {
    id: 195,
    question: "Which set introduced the concept of 'Talents' (Light, Shadow, Elemental) to hero design?",
    options: ["Arcane Rising", "Monarch", "Crucible of War", "Welcome to Rathe"],
    correctIndex: 1,
    category: "history",
  },
  {
    id: 196,
    question: "The 'Classic Battles' product line was designed for what purpose?",
    options: [
      "Tournament-level constructed decks",
      "Collector's edition reprints",
      "Online play only",
      "Two-player starter experience with pre-built decks for learning the game",
    ],
    correctIndex: 3,
    category: "history",
  },
  {
    id: 197,
    question: "How many classes were available when Flesh and Blood first launched with Welcome to Rathe?",
    options: ["4", "2", "6", "8"],
    correctIndex: 0,
    category: "history",
  },
  {
    id: 198,
    question: "What were the original four classes in Welcome to Rathe?",
    options: [
      "Wizard, Ranger, Mechanologist, Runeblade",
      "Warrior, Ninja, Brute, Guardian",
      "Illusionist, Warrior, Ninja, Brute",
      "Guardian, Wizard, Assassin, Ranger",
    ],
    correctIndex: 1,
    category: "history",
  },
  {
    id: 199,
    question: "Crucible of War was notable for introducing which popular card types?",
    options: [
      "Hero cards and weapons",
      "Token cards only",
      "Talent cards",
      "Generic cards usable by any hero and powerful Majestic/Legendary equipment",
    ],
    correctIndex: 3,
    category: "history",
  },
  {
    id: 200,
    question: "What was significant about the 'Unlimited' edition printings of early FaB sets?",
    options: [
      "They were more rare than first editions",
      "They made key cards accessible by providing a larger print run without Cold Foils",
      "They were only sold in New Zealand",
      "They had different gameplay rules",
    ],
    correctIndex: 1,
    category: "history",
  },
  {
    id: 201,
    question: "Which set was released in late 2023 and focused on the Metrix region?",
    options: ["Bright Lights", "Outsiders", "Dynasty", "Heavy Hitters"],
    correctIndex: 0,
    category: "history",
  },
  {
    id: 202,
    question: "Outsiders was notable for introducing which new classes?",
    options: [
      "Illusionist and Runeblade",
      "Guardian and Warrior",
      "Assassin and Pirate-themed Ranger",
      "Mechanologist and Wizard",
    ],
    correctIndex: 2,
    category: "history",
  },
  {
    id: 203,
    question: "What is 'Cold Foil' in Flesh and Blood?",
    options: [
      "A premium foil treatment exclusive to first edition printings",
      "A type of card sleeve",
      "A card that deals ice damage",
      "A Legendary card rarity tier",
    ],
    correctIndex: 0,
    category: "history",
  },
  {
    id: 204,
    question: "The first Flesh and Blood Pro Tour was held in which city?",
    options: ["Auckland", "Las Vegas", "Tokyo", "New Jersey"],
    correctIndex: 3,
    category: "history",
  },
  {
    id: 205,
    question: "Which rarity tier is the highest in Flesh and Blood?",
    options: ["Legendary", "Fabled", "Majestic", "Super Rare"],
    correctIndex: 1,
    category: "history",
  },
];
