import type { Achievement } from "@/types";

export const ADMIN_BADGES: Achievement[] = [
  {
    id: "badge_pioneer",
    name: "Pioneer",
    icon: "rocket",
    rarity: "legendary",
    category: "special",
    description: "Among the first to join FaB Stats",
  },
  {
    id: "badge_early_adopter",
    name: "Early Adopter",
    icon: "seedling",
    rarity: "epic",
    category: "special",
    description: "Joined FaB Stats in its early days",
  },
  {
    id: "badge_bug_hunter",
    name: "Bug Hunter",
    icon: "bug",
    rarity: "rare",
    category: "special",
    description: "Found and reported a meaningful bug",
  },
  {
    id: "badge_visionary",
    name: "Visionary",
    icon: "lightbulb",
    rarity: "epic",
    category: "special",
    description: "Suggested a feature that became reality",
  },
  {
    id: "badge_creator",
    name: "Creator",
    icon: "crown",
    rarity: "legendary",
    category: "special",
    description: "Built FaB Stats",
  },
  // Community
  {
    id: "badge_ambassador",
    name: "Ambassador",
    icon: "horn",
    rarity: "epic",
    category: "special",
    description: "Helped spread FaB Stats to the community",
  },
  {
    id: "badge_mentor",
    name: "Mentor",
    icon: "book",
    rarity: "rare",
    category: "special",
    description: "Helped other players improve their game",
  },
  {
    id: "badge_hype_machine",
    name: "Hype Machine",
    icon: "megaphone",
    rarity: "uncommon",
    category: "special",
    description: "Always hyping up events and players",
  },
  {
    id: "badge_community_pillar",
    name: "Community Pillar",
    icon: "pillar",
    rarity: "legendary",
    category: "special",
    description: "A cornerstone of the FaB community",
  },
  {
    id: "badge_welcome_wagon",
    name: "Welcome Wagon",
    icon: "wave",
    rarity: "uncommon",
    category: "special",
    description: "Known for welcoming new players",
  },
  {
    id: "badge_social_butterfly",
    name: "Social Butterfly",
    icon: "butterfly",
    rarity: "common",
    category: "special",
    description: "Active in chat, friends, and social features",
  },
  // Competitive
  {
    id: "badge_road_warrior",
    name: "Road Warrior",
    icon: "compass",
    rarity: "rare",
    category: "special",
    description: "Travels far and wide to compete",
  },
  {
    id: "badge_grinder",
    name: "Grinder",
    icon: "flame",
    rarity: "uncommon",
    category: "special",
    description: "Plays a ton of matches every week",
  },
  {
    id: "badge_dark_horse",
    name: "Dark Horse",
    icon: "horse",
    rarity: "rare",
    category: "special",
    description: "Consistently surprises with strong finishes",
  },
  {
    id: "badge_ironman",
    name: "Iron Will",
    icon: "shield",
    rarity: "epic",
    category: "special",
    description: "Plays through adversity and never gives up",
  },
  {
    id: "badge_clutch_player",
    name: "Clutch Player",
    icon: "bolt",
    rarity: "rare",
    category: "special",
    description: "Known for winning in pressure moments",
  },
  // Personality
  {
    id: "badge_storyteller",
    name: "Storyteller",
    icon: "scroll",
    rarity: "uncommon",
    category: "special",
    description: "Writes amazing match notes and event recaps",
  },
  {
    id: "badge_analyst",
    name: "Analyst",
    icon: "chart",
    rarity: "rare",
    category: "special",
    description: "Deep diver into stats and meta analysis",
  },
  {
    id: "badge_showman",
    name: "Showman",
    icon: "masks",
    rarity: "uncommon",
    category: "special",
    description: "Brings flair and personality to every game",
  },
  {
    id: "badge_zen_master",
    name: "Zen Master",
    icon: "lotus",
    rarity: "epic",
    category: "special",
    description: "Always calm, collected, and sportsmanlike",
  },
  {
    id: "badge_mad_scientist",
    name: "Mad Scientist",
    icon: "flask",
    rarity: "rare",
    category: "special",
    description: "Known for wild and experimental deckbuilding",
  },
  // Contribution
  {
    id: "badge_beta_tester",
    name: "Beta Tester",
    icon: "flask",
    rarity: "uncommon",
    category: "special",
    description: "Tested new features before public release",
  },
  {
    id: "badge_data_champion",
    name: "Data Champion",
    icon: "list",
    rarity: "rare",
    category: "special",
    description: "Contributed accurate and detailed match data",
  },
  {
    id: "badge_feedback_hero",
    name: "Feedback Hero",
    icon: "chat",
    rarity: "uncommon",
    category: "special",
    description: "Consistently provides thoughtful feedback",
  },
  // Seasonal
  {
    id: "badge_worlds_witness",
    name: "Worlds Witness",
    icon: "globe",
    rarity: "epic",
    category: "special",
    description: "Attended or followed a World Championship",
  },
  {
    id: "badge_holiday_hero",
    name: "Holiday Hero",
    icon: "snowflake",
    rarity: "uncommon",
    category: "special",
    description: "Active on FaB Stats during the holidays",
  },
  {
    id: "badge_launch_day",
    name: "Launch Day",
    icon: "rocket",
    rarity: "epic",
    category: "special",
    description: "Was there on launch day",
  },
  // Fun
  {
    id: "badge_salt_lord",
    name: "Salt Lord",
    icon: "salt",
    rarity: "common",
    category: "special",
    description: "Famously salty about losses (in a fun way)",
  },
  {
    id: "badge_meme_lord",
    name: "Meme Lord",
    icon: "jester",
    rarity: "uncommon",
    category: "special",
    description: "Peak humor. Peak content.",
  },
  {
    id: "badge_night_owl",
    name: "Night Owl",
    icon: "moon",
    rarity: "common",
    category: "special",
    description: "Logs matches in the wee hours",
  },
  {
    id: "badge_lucky_charm",
    name: "Lucky Charm",
    icon: "clover",
    rarity: "common",
    category: "special",
    description: "Suspiciously good luck",
  },
];

export function getBadgeById(id: string): Achievement | undefined {
  return ADMIN_BADGES.find((b) => b.id === id);
}

export function getBadgesForIds(ids: string[]): Achievement[] {
  return ids.map((id) => getBadgeById(id)).filter(Boolean) as Achievement[];
}

export function getAllBadges(): Achievement[] {
  return ADMIN_BADGES;
}
