import type { WordEntry } from "./types";

export const WORD_BANK: WordEntry[] = [
  // ── Heroes ──
  { word: "BRAVO", clue: "Star of Aria, Guardian of the Old", category: "hero" },
  { word: "KATSU", clue: "Ninja hero who masters the way of the claw", category: "hero" },
  { word: "RHINAR", clue: "Brute from the Savage Lands", category: "hero" },
  { word: "DASH", clue: "Young Mechanologist inventor from Metrix", category: "hero" },
  { word: "AZALEA", clue: "Ranger assassin from the Pits", category: "hero" },
  { word: "VISERAI", clue: "Runeblade who escaped the Demonastery", category: "hero" },
  { word: "KANO", clue: "Wizard who wields raw arcane energy", category: "hero" },
  { word: "LEXI", clue: "Elemental Ranger from Aria", category: "hero" },
  { word: "PRISM", clue: "Light Illusionist from Solana", category: "hero" },
  { word: "CHANE", clue: "Shadow Runeblade bound to the Shadows", category: "hero" },
  { word: "BOLTYN", clue: "Light Warrior and champion of Solana", category: "hero" },
  { word: "LEVIA", clue: "Shadow Brute consumed by blood debt", category: "hero" },
  { word: "OLDHIM", clue: "Ancient Ice Guardian of Aria", category: "hero" },
  { word: "BRIAR", clue: "Elemental Runeblade of the Rosetta", category: "hero" },
  { word: "DROMAI", clue: "Draconic Illusionist who summons dragons", category: "hero" },
  { word: "FAI", clue: "Draconic Ninja from Volcor", category: "hero" },
  { word: "KASSAI", clue: "Cintari Warrior dual-wielding swords", category: "hero" },
  { word: "UZURI", clue: "Assassin from the Pits of the Demonastery", category: "hero" },
  { word: "ARAKNI", clue: "Mysterious Assassin, identity unknown", category: "hero" },
  { word: "ENIGMA", clue: "Mystic Illusionist from the East", category: "hero" },
  { word: "NUU", clue: "Mystic Assassin with dual identity", category: "hero" },
  { word: "OSCILIO", clue: "Lightning Wizard of Metrix", category: "hero" },
  { word: "AURORA", clue: "Elemental Runeblade of ice and lightning", category: "hero" },
  { word: "FLORIAN", clue: "Earth Runeblade connected to nature", category: "hero" },
  { word: "TERRA", clue: "Earth Guardian who protects the wild", category: "hero" },
  { word: "VERDANCE", clue: "Earth Illusionist from the wilds", category: "hero" },
  { word: "KAYO", clue: "Brute who fights with raw fury", category: "hero" },
  { word: "ZEN", clue: "Ninja master of focus and flow", category: "hero" },
  { word: "BENJI", clue: "Young Ninja with quick reflexes", category: "hero" },
  { word: "MELODY", clue: "Bard hero who sings songs of power", category: "hero" },
  { word: "OLYMPIA", clue: "Warrior hero of legendary strength", category: "hero" },
  { word: "CINDRA", clue: "Draconic Wizard wreathed in flame", category: "hero" },
  { word: "BETSY", clue: "Guardian hero with a gentle heart", category: "hero" },
  { word: "VICTOR", clue: "Guardian who fights for honor", category: "hero" },
  { word: "BREVANT", clue: "Guardian shielding allies in battle", category: "hero" },
  { word: "VALDA", clue: "Guardian from the frozen north", category: "hero" },
  { word: "IRA", clue: "Young Ninja, the simplest hero to learn", category: "hero" },
  { word: "BLAZE", clue: "Draconic Wizard burning bright", category: "hero" },
  { word: "RIPTIDE", clue: "Pirate Ranger sailing the seas", category: "hero" },

  // ── Classes ──
  { word: "GUARDIAN", clue: "Defensive class wielding shields and hammers", category: "class" },
  { word: "WARRIOR", clue: "Weapon-focused melee combat class", category: "class" },
  { word: "NINJA", clue: "Fast-striking class with combo chains", category: "class" },
  { word: "BRUTE", clue: "Class known for intimidation and fury", category: "class" },
  { word: "WIZARD", clue: "Arcane damage dealer class", category: "class" },
  { word: "RANGER", clue: "Class attacking from range with arrows", category: "class" },
  { word: "ASSASSIN", clue: "Stealth-based class from the underworld", category: "class" },
  { word: "BARD", clue: "Musical class that buffs with songs", category: "class" },
  { word: "PIRATE", clue: "Seafaring class plundering for loot", category: "class" },
  { word: "MERCHANT", clue: "Trading class dealing in goods", category: "class" },

  // ── Talents ──
  { word: "DRACONIC", clue: "Dragon-themed talent from Volcor", category: "talent" },
  { word: "SHADOW", clue: "Dark talent from the Demonastery", category: "talent" },
  { word: "LIGHT", clue: "Radiant talent from Solana", category: "talent" },
  { word: "ICE", clue: "Freezing talent found in the north of Aria", category: "talent" },
  { word: "EARTH", clue: "Nature-based talent of growth and roots", category: "talent" },
  { word: "MYSTIC", clue: "Arcane talent of the Nether realms", category: "talent" },
  { word: "ROYAL", clue: "Noble talent of the Uprising era", category: "talent" },
  { word: "CHAOS", clue: "Unpredictable talent of disorder", category: "talent" },

  // ── Keywords ──
  { word: "DOMINATE", clue: "Keyword: defend with only one card from hand", category: "keyword" },
  { word: "CRUSH", clue: "Keyword: triggers when attack is not fully defended", category: "keyword" },
  { word: "REPRISE", clue: "Keyword: triggers when opponent has defended", category: "keyword" },
  { word: "COMBO", clue: "Keyword: requires specific card played before it", category: "keyword" },
  { word: "BOOST", clue: "Mechanologist keyword: banish top of deck for bonus", category: "keyword" },
  { word: "STEALTH", clue: "Keyword: cannot be defended from arsenal", category: "keyword" },
  { word: "WARD", clue: "Keyword: prevents targeting by opponent", category: "keyword" },
  { word: "TEMPER", clue: "Keyword: place a counter, destroy when threshold met", category: "keyword" },
  { word: "HEAVE", clue: "Keyword: trigger at end of turn if card wasn't played", category: "keyword" },
  { word: "SURGE", clue: "Keyword: bonus when played as second action or later", category: "keyword" },
  { word: "FREEZE", clue: "Ice keyword: locks opponent's cards for a turn", category: "keyword" },
  { word: "FUSION", clue: "Reveal a card from hand to power up an attack", category: "keyword" },
  { word: "CHARGE", clue: "Keyword: put into soul when played from hand", category: "keyword" },
  { word: "FLOW", clue: "Lightning keyword granting additional effects", category: "keyword" },
  { word: "BOND", clue: "Earth keyword connecting to nature's power", category: "keyword" },
  { word: "OPT", clue: "Keyword: look at top cards and rearrange", category: "keyword" },
  { word: "RELOAD", clue: "Ranger keyword: put an arrow into arsenal", category: "keyword" },
  { word: "AMBUSH", clue: "Keyword: can be played from hand as defense", category: "keyword" },
  { word: "TOWER", clue: "Guardian keyword for stacking defenses", category: "keyword" },
  { word: "CRANK", clue: "Mechanologist keyword: rotate for power", category: "keyword" },
  { word: "MARK", clue: "Assassin keyword: place a contract on target", category: "keyword" },
  { word: "AMP", clue: "Wizard keyword: boost the next arcane damage", category: "keyword" },
  { word: "MIRAGE", clue: "Illusionist keyword creating false images", category: "keyword" },
  { word: "HEAVY", clue: "Modifier making an attack harder to defend", category: "keyword" },
  { word: "GALVANIZE", clue: "Keyword: grants action an additional go again", category: "keyword" },
  { word: "AWAKEN", clue: "Earth keyword: trigger powerful nature effects", category: "keyword" },
  { word: "PROTECT", clue: "Guardian keyword defending allies", category: "keyword" },
  { word: "NEGATE", clue: "Counter an effect or action", category: "keyword" },
  { word: "RUPTURE", clue: "Keyword dealing extra damage through armor", category: "keyword" },
  { word: "SCRAP", clue: "Mechanologist keyword recycling items", category: "keyword" },
  { word: "STEAL", clue: "Pirate keyword taking opponent's resources", category: "keyword" },
  { word: "WAGER", clue: "Keyword: bet on the outcome for bonus effects", category: "keyword" },
  { word: "SPECTRA", clue: "Illusionist keyword creating spectral images", category: "keyword" },
  { word: "QUELL", clue: "Reduce the cost of your next card", category: "keyword" },

  // ── Lore Locations ──
  { word: "ARIA", clue: "Continent of ice, home to Guardians and Rangers", category: "lore" },
  { word: "METRIX", clue: "Steampunk city of Mechanologists", category: "lore" },
  { word: "SOLANA", clue: "City of Light and birthplace of Illusionists", category: "lore" },
  { word: "VOLCOR", clue: "Volcanic realm of Draconic heroes", category: "lore" },
  { word: "RATHE", clue: "The world where Flesh and Blood takes place", category: "lore" },
  { word: "SAVAGE", clue: "___ Lands: Rhinar's dangerous homeland", category: "lore" },
  { word: "PITS", clue: "Underground realm of Assassins", category: "lore" },

  // ── Card Types & Equipment ──
  { word: "ATTACK", clue: "Most common action card type", category: "type" },
  { word: "WEAPON", clue: "Equipment you strike with each turn", category: "type" },
  { word: "INSTANT", clue: "Card playable during any window", category: "type" },
  { word: "AURA", clue: "Persistent enchantment card type", category: "type" },
  { word: "SWORD", clue: "Weapon subtype used by Warriors", category: "type" },
  { word: "DAGGER", clue: "Weapon subtype: small blade for quick strikes", category: "type" },
  { word: "BOW", clue: "Weapon subtype for Rangers", category: "type" },
  { word: "STAFF", clue: "Weapon subtype for Wizards and casters", category: "type" },
  { word: "AXE", clue: "Weapon subtype for Brutes and Guardians", category: "type" },
  { word: "HAMMER", clue: "Weapon subtype: heavy crushing weapon", category: "type" },
  { word: "SHIELD", clue: "Off-hand equipment for blocking", category: "type" },
  { word: "CHEST", clue: "Equipment slot protecting your torso", category: "type" },
  { word: "HEAD", clue: "Equipment slot for helmets and hoods", category: "type" },
  { word: "LEGS", clue: "Equipment slot worn below the waist", category: "type" },
  { word: "CLAW", clue: "Weapon subtype for Ninjas", category: "type" },
  { word: "SCYTHE", clue: "Weapon subtype: curved blade of reapers", category: "type" },
  { word: "FLAIL", clue: "Weapon subtype: chain and ball", category: "type" },
  { word: "GUN", clue: "Weapon subtype for ranged Mechanologists", category: "type" },
  { word: "PISTOL", clue: "Weapon subtype: one-handed firearm", category: "type" },
  { word: "TOKEN", clue: "Generated card that exists temporarily", category: "type" },
  { word: "ALLY", clue: "Companion creature fighting alongside you", category: "type" },
  { word: "ANGEL", clue: "Celestial creature summoned by Light heroes", category: "type" },
  { word: "DEMON", clue: "Dark creature summoned by Shadow heroes", category: "type" },
  { word: "DRAGON", clue: "Draconic creature summoned by Dromai", category: "type" },
  { word: "FIGMENT", clue: "Illusory creation that breaks to 6+ power", category: "type" },

  // ── Game Mechanics ──
  { word: "PITCH", clue: "Place a card in the pitch zone for resources", category: "mechanic" },
  { word: "BANISH", clue: "Zone for face-up removed cards", category: "mechanic" },
  { word: "BLOCK", clue: "Defend by playing cards from hand", category: "mechanic" },
  { word: "ARCANE", clue: "Damage type bypassing physical defense", category: "mechanic" },
  { word: "DEFENSE", clue: "Bottom-right value on cards for blocking", category: "mechanic" },
  { word: "ARSENAL", clue: "Zone for storing one face-down card", category: "mechanic" },
  { word: "DECK", clue: "Your main pile of 60+ cards", category: "mechanic" },
  { word: "SOUL", clue: "Zone under your hero for Light/Shadow cards", category: "mechanic" },
  { word: "COMBAT", clue: "___ chain: the sequence of attacks in a turn", category: "mechanic" },
  { word: "CHAIN", clue: "Linked sequence of attack actions", category: "mechanic" },
  { word: "POWER", clue: "Top-left value: how hard an attack hits", category: "mechanic" },
  { word: "COST", clue: "Resource amount needed to play a card", category: "mechanic" },
  { word: "HERO", clue: "Your main character card with life total", category: "mechanic" },
  { word: "LIFE", clue: "Your health total — hit zero and you lose", category: "mechanic" },
  { word: "DRAW", clue: "Action of pulling cards from your deck", category: "mechanic" },
  { word: "TURN", clue: "One cycle of play: start, action, end", category: "mechanic" },
  { word: "HAND", clue: "Cards you hold and can play or defend with", category: "mechanic" },

  // ── Rarities ──
  { word: "COMMON", clue: "Most basic card rarity, easy to find", category: "rarity" },
  { word: "RARE", clue: "Mid-tier card rarity", category: "rarity" },
  { word: "MAJESTIC", clue: "Premium rarity with gold-bordered cards", category: "rarity" },
  { word: "FABLED", clue: "Rarest of all — mythically powerful cards", category: "rarity" },
  { word: "MARVEL", clue: "Ultra-rare alternative art rarity", category: "rarity" },
  { word: "PROMO", clue: "Special limited-edition card rarity", category: "rarity" },

  // ── Sets ──
  { word: "MONARCH", clue: "Set that introduced Light and Shadow talents", category: "set" },
  { word: "UPRISING", clue: "Set that brought Dromai and Fai to the game", category: "set" },
  { word: "DYNASTY", clue: "Set featuring Emperor and Royals of Volcor", category: "set" },
  { word: "ROSETTA", clue: "Set introducing Earth heroes and new bonds", category: "set" },
  { word: "EVERFEST", clue: "Carnival-themed supplemental set", category: "set" },

  // ── Formats ──
  { word: "BLITZ", clue: "Fast format: Young heroes, 40-card decks", category: "format" },
  { word: "DRAFT", clue: "Limited: build a deck from opened packs", category: "format" },
  { word: "SEALED", clue: "Limited: build from 6 booster packs", category: "format" },
  { word: "CLASH", clue: "Casual multiplayer format", category: "format" },

  // ── Events ──
  { word: "CALLING", clue: "Major competitive FaB tournament series", category: "event" },
  { word: "ARMORY", clue: "Weekly store-level FaB event", category: "event" },
  { word: "SKIRMISH", clue: "Local competitive FaB event", category: "event" },
  { word: "WORLDS", clue: "The ultimate FaB championship event", category: "event" },

  // ── Pitch Colors ──
  { word: "RED", clue: "Pitch strip color: 0 resources, highest power", category: "mechanic" },
  { word: "YELLOW", clue: "Pitch strip color: 2 resources, balanced", category: "mechanic" },
  { word: "BLUE", clue: "Pitch strip color: 3 resources, best for pitching", category: "mechanic" },

  // ── General FaB Terms ──
  { word: "YOUNG", clue: "Hero age used in Blitz format", category: "general" },
  { word: "ADULT", clue: "Hero age used in Classic Constructed", category: "general" },
  { word: "FOIL", clue: "Shiny premium version of a card", category: "general" },
  { word: "COLD", clue: "___ Foil: the rarest card finish", category: "general" },
  { word: "ENDGAME", clue: "The late phase where decks are nearly empty", category: "general" },
  { word: "FATIGUE", clue: "Strategy of grinding the opponent's resources", category: "general" },
  { word: "AGGRO", clue: "Strategy focusing on fast, aggressive attacks", category: "general" },
  { word: "TEMPO", clue: "The pace and rhythm of play", category: "general" },
  { word: "VALUE", clue: "Card advantage and resource efficiency", category: "general" },
  { word: "PUMP", clue: "Buff an attack's power with additional cards", category: "general" },
  { word: "SWING", clue: "A weapon attack action", category: "general" },
  { word: "SLOT", clue: "An equipment position on your hero", category: "general" },
  { word: "ZONE", clue: "A game area: hand, deck, graveyard, etc.", category: "general" },
  { word: "STACK", clue: "Multiple cards defending a single attack", category: "general" },
  { word: "BREAK", clue: "Blade ___: keyword destroying equipment", category: "general" },
  { word: "MELD", clue: "Keyword combining two cards into one effect", category: "general" },
  { word: "LUTE", clue: "Musical weapon subtype for Bards", category: "type" },
  { word: "FIDDLE", clue: "String instrument weapon for Bards", category: "type" },
  { word: "SONG", clue: "Bard card subtype that creates melodies", category: "type" },
  { word: "TRAP", clue: "Ranger card subtype set face-down", category: "type" },
  { word: "ARROW", clue: "Ranger ammunition subtype", category: "type" },
  { word: "ORB", clue: "Off-hand equipment for arcane users", category: "type" },
  { word: "QUIVER", clue: "Equipment holding arrows for Rangers", category: "type" },
  { word: "GEM", clue: "Collectible item type in the game", category: "type" },
  { word: "BOOK", clue: "Equipment subtype for knowledge-seekers", category: "type" },
  { word: "SCROLL", clue: "Item subtype containing written magic", category: "type" },
];
