// AUTO-GENERATED by scripts/gen-cosmetic-seed.ts — do not edit by hand.
// Regenerate:  npx tsx scripts/gen-cosmetic-seed.ts
// Pure data (no @/* imports) so the cosmetics-wallet Netlify function can bundle it.
// These are the DEFAULT SKUs (price/isActive/rarity + gacha pool/weight); a
// Firestore cosmeticCatalog/{id} doc (admin override) takes precedence at purchase time.
export type SeedRarity = "common" | "uncommon" | "rare" | "epic" | "legendary";

export interface CosmeticSeedEntry {
  price: number;
  isActive: boolean;
  rarity: SeedRarity;
  gachaPool?: string;
  gachaWeight?: number;
}

export const COSMETIC_SEED: Record<string, CosmeticSeedEntry> = {
  "aura-corona-gold": { price: 12000, isActive: true, rarity: "legendary", gachaPool: "premium", gachaWeight: 8 },
  "aura-halo-bronze": { price: 300, isActive: true, rarity: "common", gachaPool: "standard", gachaWeight: 1000 },
  "aura-halo-silver": { price: 800, isActive: true, rarity: "uncommon", gachaPool: "standard", gachaWeight: 400 },
  "aura-motes-gold": { price: 2000, isActive: true, rarity: "rare", gachaPool: "standard", gachaWeight: 150 },
  "aura-motes-silver": { price: 800, isActive: true, rarity: "uncommon", gachaPool: "standard", gachaWeight: 400 },
  "aura-rays-gold": { price: 2000, isActive: true, rarity: "rare", gachaPool: "standard", gachaWeight: 150 },
  "aura-sunburst-mythic": { price: 5000, isActive: true, rarity: "epic", gachaPool: "premium", gachaWeight: 40 },
  "bg-arakni": { price: 5000, isActive: true, rarity: "epic" },
  "bg-hunted": { price: 2000, isActive: true, rarity: "rare" },
  "bg-rathe-alt": { price: 800, isActive: true, rarity: "uncommon" },
  "comp-crescent-silver": { price: 800, isActive: true, rarity: "uncommon", gachaPool: "standard", gachaWeight: 400 },
  "comp-dragon-sovereign": { price: 12000, isActive: true, rarity: "legendary", gachaPool: "premium", gachaWeight: 8 },
  "comp-fleur-bronze": { price: 300, isActive: true, rarity: "common", gachaPool: "standard", gachaWeight: 1000 },
  "comp-lion-mythic": { price: 5000, isActive: true, rarity: "epic", gachaPool: "premium", gachaWeight: 40 },
  "comp-phoenix-mythic": { price: 5000, isActive: true, rarity: "epic", gachaPool: "premium", gachaWeight: 40 },
  "comp-rose-bronze": { price: 300, isActive: true, rarity: "common", gachaPool: "standard", gachaWeight: 1000 },
  "comp-stag-gold": { price: 2000, isActive: true, rarity: "rare", gachaPool: "standard", gachaWeight: 150 },
  "comp-sun-gold": { price: 2000, isActive: true, rarity: "rare", gachaPool: "standard", gachaWeight: 150 },
  "comp-wolf-silver": { price: 800, isActive: true, rarity: "uncommon", gachaPool: "standard", gachaWeight: 400 },
  "cursor-crystal": { price: 2000, isActive: true, rarity: "rare" },
  "cursor-golden": { price: 800, isActive: true, rarity: "uncommon" },
  "cursor-rainbow": { price: 5000, isActive: true, rarity: "epic" },
  "frame-filigree-gold": { price: 2000, isActive: true, rarity: "rare", gachaPool: "standard", gachaWeight: 150 },
  "frame-filigree-mythic": { price: 5000, isActive: true, rarity: "epic", gachaPool: "premium", gachaWeight: 40 },
  "frame-heraldic-gold": { price: 2000, isActive: true, rarity: "rare", gachaPool: "standard", gachaWeight: 150 },
  "frame-keyline-bronze": { price: 300, isActive: true, rarity: "common", gachaPool: "standard", gachaWeight: 1000 },
  "frame-laurel-silver": { price: 800, isActive: true, rarity: "uncommon", gachaPool: "standard", gachaWeight: 400 },
  "frame-rope-silver": { price: 800, isActive: true, rarity: "uncommon", gachaPool: "standard", gachaWeight: 400 },
  "frame-runic-mythic": { price: 5000, isActive: true, rarity: "epic", gachaPool: "premium", gachaWeight: 40 },
  "frame-sovereign-gold": { price: 12000, isActive: true, rarity: "legendary", gachaPool: "premium", gachaWeight: 8 },
  "frame-studded-bronze": { price: 300, isActive: true, rarity: "common", gachaPool: "standard", gachaWeight: 1000 },
  "plate-diamonds-gold": { price: 2000, isActive: true, rarity: "rare", gachaPool: "standard", gachaWeight: 150 },
  "plate-guilloche-gold": { price: 2000, isActive: true, rarity: "rare", gachaPool: "standard", gachaWeight: 150 },
  "plate-laurel-silver": { price: 800, isActive: true, rarity: "uncommon", gachaPool: "standard", gachaWeight: 400 },
  "plate-plain-silver": { price: 800, isActive: true, rarity: "uncommon", gachaPool: "standard", gachaWeight: 400 },
  "plate-rule-bronze": { price: 300, isActive: true, rarity: "common", gachaPool: "standard", gachaWeight: 1000 },
  "plate-runes-bronze": { price: 300, isActive: true, rarity: "common", gachaPool: "standard", gachaWeight: 1000 },
  "plate-sovereign-gold": { price: 12000, isActive: true, rarity: "legendary", gachaPool: "premium", gachaWeight: 8 },
  "plate-tablet-mythic": { price: 5000, isActive: true, rarity: "epic", gachaPool: "premium", gachaWeight: 40 },
  "trophy-bh-helm": { price: 800, isActive: true, rarity: "uncommon" },
  "trophy-pt-standard": { price: 2000, isActive: true, rarity: "rare" },
  "trophy-worlds-crown": { price: 5000, isActive: true, rarity: "epic" },
};
