/**
 * Regenerates src/lib/games/frozen-pool-data-v4.ts from the INSTALLED
 * @flesh-and-blood/cards package. Run only as part of a deliberate pool
 * refresh: capture fixtures first (verify-frozen-pool.ts), regenerate, set the
 * cutover in frozen-pool.ts to a FUTURE UTC date, and compare — dates before
 * the cutover must stay byte-identical.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { allHeroes } from "../src/lib/heroes";
import { allCards } from "../src/lib/cards";

const pkgVersion = (
  JSON.parse(readFileSync("node_modules/@flesh-and-blood/cards/package.json", "utf8")) as { version: string }
).version;

const heroes = allHeroes.map((h) => ({ name: h.name, legalFormats: h.legalFormats }));
const cardIds = allCards.map((c) => c.cardIdentifier);

const out = `// AUTO-GENERATED by scripts/gen-frozen-pool-v4.ts — DO NOT EDIT BY HAND.
// Frozen snapshot of the @flesh-and-blood/cards \`${pkgVersion}\` daily-game pools. Games use
// this pool for dates ON/AFTER the cutover in frozen-pool.ts; earlier dates keep the v3
// snapshot so already-played puzzles never remap. Regenerating this file (a future v5) is a
// deliberate, reviewed break: run scripts/verify-frozen-pool.ts capture BEFORE, regen, move
// the cutover to a future UTC date, then compare — pre-cutover dates must be byte-identical.
/* eslint-disable */

export const FROZEN_HEROES_V4: { name: string; legalFormats: string[] }[] = ${JSON.stringify(heroes)};

export const FROZEN_CARD_IDS_V4: string[] = ${JSON.stringify(cardIds)};
`;

writeFileSync("src/lib/games/frozen-pool-data-v4.ts", out);
console.log(`wrote frozen-pool-data-v4.ts: ${heroes.length} heroes, ${cardIds.length} cards (package ${pkgVersion})`);
