/**
 * Generates netlify/functions/lib/cosmetic-seed.ts — a PURE-DATA id→{price,isActive}
 * map so the cosmetics-wallet Netlify function can price purchases server-side
 * WITHOUT the Firestore catalog having been seeded (the default SKUs live in code,
 * not the DB). Firestore cosmeticCatalog stays an optional admin override layer.
 * The generated file has NO `@/*` imports so esbuild can bundle it into the function.
 *
 *   npx tsx scripts/gen-cosmetic-seed.ts
 */
import { writeFileSync } from "node:fs";
import { SEED_COSMETICS } from "../src/lib/cosmetics/seed-cosmetics";

const entries = [...SEED_COSMETICS].sort((a, b) => a.id.localeCompare(b.id));

const body = entries
  .map((c) => {
    const parts = [
      `price: ${Math.max(0, Math.round(c.price))}`,
      `isActive: ${c.isActive !== false}`,
      `rarity: ${JSON.stringify(c.rarity)}`,
    ];
    if (c.gachaPool) parts.push(`gachaPool: ${JSON.stringify(c.gachaPool)}`);
    if (typeof c.gachaWeight === "number") parts.push(`gachaWeight: ${Math.max(0, Math.round(c.gachaWeight))}`);
    return `  ${JSON.stringify(c.id)}: { ${parts.join(", ")} },`;
  })
  .join("\n");

const out = `// AUTO-GENERATED by scripts/gen-cosmetic-seed.ts — do not edit by hand.
// Regenerate:  npx tsx scripts/gen-cosmetic-seed.ts
// Pure data (no @/* imports) so the cosmetics-wallet Netlify function can bundle it.
// These are the DEFAULT SKUs (price/isActive/rarity + gacha pool/weight); a
// Firestore cosmeticCatalog/{id} doc (admin override) takes precedence at purchase time.
export type SeedRarity = "common" | "uncommon" | "rare" | "epic" | "legendary";

export interface CosmeticSeedEntry {
  price: number;
  isActive: boolean;
  rarity: SeedRarity;
  gachaPool?: string;
  gachaWeight?: number;
}

export const COSMETIC_SEED: Record<string, CosmeticSeedEntry> = {
${body}
};
`;

writeFileSync("netlify/functions/lib/cosmetic-seed.ts", out, "utf8");
console.log(`Wrote netlify/functions/lib/cosmetic-seed.ts (${entries.length} SKUs)`);
