/**
 * Generates netlify/functions/lib/achievement-rarity.ts — a PURE-DATA id→rarity
 * map the cosmetics-wallet Netlify function uses to price the one-time
 * achievement coin payout. The generated file has NO `@/*` imports so esbuild
 * can bundle it into the function; regenerate whenever achievements change.
 *
 *   npx tsx scripts/gen-achievement-rarity.ts
 */
import { writeFileSync } from "node:fs";
import { getAllAchievements } from "../src/lib/achievements";

const entries = getAllAchievements()
  .map((a) => [a.id, a.rarity] as const)
  .sort((a, b) => a[0].localeCompare(b[0]));

const body = entries.map(([id, r]) => `  ${JSON.stringify(id)}: ${JSON.stringify(r)},`).join("\n");

const out = `// AUTO-GENERATED by scripts/gen-achievement-rarity.ts — do not edit by hand.
// Regenerate:  npx tsx scripts/gen-achievement-rarity.ts
// Pure data (no @/* imports) so the cosmetics-wallet Netlify function can bundle it.
export type Rarity = "common" | "uncommon" | "rare" | "epic" | "legendary";

export const ACHIEVEMENT_RARITY: Record<string, Rarity> = {
${body}
};
`;

writeFileSync("netlify/functions/lib/achievement-rarity.ts", out, "utf8");
console.log(`Wrote netlify/functions/lib/achievement-rarity.ts (${entries.length} achievements)`);
